### ISSUE TITLE
ReceiptUtility returns not original_receipt_id

### ISSUE THREAD

**Issue by svycka** [hoels/app-store-server-library-php#1]
when I request the status of all active subscriptions I get the original id so maybe it's possible to extract original_transaction_id? 

```php
$receiptUtil = new ReceiptUtility();
$transactionId = $receiptUtil->extractTransactionIdFromAppReceipt("MII25AY....");
// Then I try
$response = $client->getAllSubscriptionStatuses($transactionId);
this returns all active subscriptions with original_transaction_id attached and I can't compare them
```

**Comment by hoels** [comment]
Hey Vytautas,

thanks for your suggestion. I am not using the ReceiptUtility myself, but I think it makes more sense to get the transaction ID instead of the original transaction ID. The [README](https://github.com/hoels/app-store-server-library-php?tab=readme-ov-file#receipt-usage) shows the intended use of the utility. With the transaction ID, you are able to request the transaction history from the App Store Server API. If the method would return the original transaction ID instead, you wouldn't be able to differentiate receipts for multiple renewals of the same subscription and you also wouldn't be able to request the transaction history.

The `getAllSubscriptionStatuses` ([API documentation](https://developer.apple.com/documentation/appstoreserverapi/get_all_subscription_statuses)) method does not only return the status of the subscription corresponding to the given transaction ID but of all subscriptions the user belonging to the transaction ID has. Therefore, the `getTransactionHistory` ([API documentation](https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history)) method is probably the one you want to use. 

I have to admit that I am not the biggest fan of how things are implemented in the ReceiptUtility. If information is already available in the receipt, I would much rather have a method to convert an app receipt into an object containing all its values. However, my library is intended to mirror the functionality of Apple's libraries and that's the way Apple decided to implement it. Therefore, I am not going to change it, unless Apple does.

The test you are mentioning in your pull request is also the same test Apple uses in their libraries. I was confused about the transaction ID "0" as well, but I still think it is a valid receipt and they just decided to use this specific transaction ID.

**Comment by svycka** [comment]
I understand your intentions and did not expect you would fix what Apple failed. But also your implementation is not exactly like Apple implemented it. 
As I understand apple library versions can return  `transaction_id` or `original_transaction_id` depending on what is found first which I don't like even more.

**Comment by hoels** [comment]
I had another look at the libraries and you are right that at least 3 of them return either the `transaction_id` or the `original_transaction_id`. However, the Python library only searches for the `transaction_id` and since my implementation is closest to the Python library, that's what I implemented as well.

I agree that this makes the behaviour even weirder and I'm confused why Apple's own libraries have such differences in their functionality and that there are no unit tests to cover this. It might be worth to open an issue in the [Python library](https://github.com/apple/app-store-server-library-python) to point out this deviation, even though the overall functionality arguably won't improve.
