### ISSUE TITLE
Do we need to verify?

### ISSUE THREAD

**Issue by PixelnomadsLtd** [hoels/app-store-server-library-php#4]
Hey!

Thanks for your code, very helpful. When i send a receipt to Apple and get the JWS in base64, why not just

`$data = explode(".", $transactions[count($transactions)-1]);
echo base64_decode($data[1]);`

and use this data. I'm not a security specialist, but what could happen, when i don't verify the data from Apple? I mean, i will send the receipt to the Apple server and get the answer, is it possible that someone in the middle can manipulate this data?

Thanks,
Steven

**Comment by hoels** [comment]
Hey Steven,

even though it's unlikely, there is always the chance of so called ["Man-in-the-middle" attacks](https://en.wikipedia.org/wiki/Man-in-the-middle_attack). It's up to you whether you are willing to take that risk, but this library is intended to make the verification as simple as possible so that developers can make their implementation as secure as possible and I would always recommend doing so.

Just to mention it for anyone having similar questions: App Store Server Notifications are a completely different scenario. When you create an API endpoint for Apple to send notifications to, this endpoint is usually publicly available. If you don't verify the payloads you receive, anyone could send anything and pretend they extended their subscription or similar.
