### ISSUE TITLE
how to load apple root certificates

### ISSUE THREAD

**Issue by tarikalalwani** [hoels/app-store-server-library-php#6]
```
function loadAppleRootCertificates() {
    
    $rootCAs = [
        "./AppleComputerRootCertificate.cer",
        "./AppleIncRootCertificate.cer",
        "./AppleRootCA-G2.cer",
        "./AppleRootCA-G3.cer"
    ];

    $loadedRootCAs = [];
   
    foreach ($rootCAs as $rootCA) {
        $x509 = new X509();
        $path = $rootCA;
        try {
            $certificate = file_get_contents($path);
            if ($certificate === false) {
                throw new Exception("Failed to read certificate file: $path");
            }
          $loadedRootCAs= $x509->loadX509($certificate);
         
        } catch (Exception $e) {
            echo $e->getMessage() . "\n";
            throw new Exception("Please add valid Apple Root Certificates.");
        }
    }
  
    return $loadedRootCAs;

}
```

Above function is not working properly

**Comment by hoels** [comment]
It‘s difficult to assist you with your issue without knowing the error output. However, I can already see two issues with your function:
- You are overwriting `$loadedRootCAs` instead of appending to the initial array.
- You are supposed to pass an array of strings containing the file contents of the certificate files. Parsing it into an `X509` object is not necessary.

I already posted an example on what the function could look like [here](https://github.com/hoels/app-store-server-library-php/issues/3#issuecomment-2052088878).

**Comment by tarikalalwani** [comment]
ok understood
